### ISSUE TITLE
!tryme works in errbot direct message but in #general channel !tryme gives below error

### ISSUE THREAD

**Issue by rachamaduguravi** [gbin/err-backend-discord#54]
16:11:17 INFO     errbot.plugins.ChatRoom   Connecting bot chatrooms
16:11:17 INFO     errbot.core               Plugin activation done.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/reflexdev/reflex/Apps/Risking/Dev/Errbot/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/reflexdev/reflex/Apps/Risking/Dev/Errbot/backend/err-backend-discord/src/err-backend-discord/err-backend-discord.py", line 131, in on_message
    err_msg.to = DiscordRoom.from_id(DiscordBackend.client, msg.channel.id)
TypeError: from_id() takes 2 positional arguments but 3 were given

**Comment by nzlosh** [comment]
Thank you for opening this issue.  I've been able to reproduce the issue and will look into how best to resolve it.
