### ISSUE TITLE
Plugin error attribute id

### ISSUE THREAD

**Issue by futex** [gbin/err-backend-discord#58]
Hello i try to run errbot through discord (my token works) but when i launch it i have these errors, does that say something to anyone?
`20:24:34` ERROR discord.client Ignoring exception in on_ready
Traceback (most recent call last):
File "./errbot-ve/lib/python3.10/site-packages/discord/[client.py](http://client.py/)", line 409, in _run_event
await coro(*args, **kwargs)
File "./errbot-ve/lib/python3.10/site-packages/err-backend-discord/[err-backend-discord.py](http://err-backend-discord.py/)", line 90, in on_ready
[self.bot](http://self.bot/)_identifier = DiscordPerson([DiscordBackend.client.user.id](http://discordbackend.client.user.id/))
File "./errbot-ve/lib/python3.10/site-packages/err-backend-discord/discordlib/[person.py](http://person.py/)", line 56, in init
raise ValueError(f"Invalid Discord user id {type(user_id)} {user_id}.")
ValueError: Invalid Discord user id <class 'int'> `XXXXXXXXXXX.`

And when i try to launch a plugin i got this error:

`20:24:45` ERROR discord.client Ignoring exception in on_message
Traceback (most recent call last):
File "./errbot-ve/lib/python3.10/site-packages/discord/[client.py](http://client.py/)", line 409, in _run_event
await coro(*args, **kwargs)
File "./errbot-ve/lib/python3.10/site-packages/err-backend-discord/[err-backend-discord.py](http://err-backend-discord.py/)", line 114, in on_message
if self.process_message(err_msg):
File "./errbot-ve/lib/python3.10/site-packages/errbot/[core.py](http://core.py/)", line 282, in process_message
if [self.is](http://self.is/)_from_self(msg):
File "./errbot-ve/lib/python3.10/site-packages/err-backend-discord/[err-backend-discord.py](http://err-backend-discord.py/)", line 139, in is_from_self
return [other.id](http://other.id/) == [self.bot](http://self.bot/)_[identifier.id](http://identifier.id/)
AttributeError: 'NoneType' object has no attribute 'id' `

**Comment by futex** [comment]
I still having this issue, and as you can see i have all the last packages version

```
errbot                  6.1.9    
discord.py              2.0.1
err-backend-discord     4.0.0
```
