### ISSUE TITLE
Issue on start with err-backend-discord

### ISSUE THREAD

**Issue by kengodwin** [gbin/err-backend-discord#59]
**Error Message**
01:52:03 ERROR    discord.client            Ignoring exception in on_ready
Traceback (most recent call last):
  File "/root/chatops/errbot/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/root/chatops/errbot/lib/python3.10/site-packages/err-backend-discord/err-backend-discord.py", line 90, in on_ready
    self.bot_identifier = DiscordPerson(DiscordBackend.client.user.id)
  File "/root/chatops/errbot/lib/python3.10/site-packages/err-backend-discord/discordlib/person.py", line 56, in __init__
    raise ValueError(f"Invalid Discord user id {type(user_id)} {user_id}.")
ValueError: Invalid Discord user id <class 'int'> 1069064502915637279.

**BOT_ADMINS**
It correctly converts @<discord>#<id> in BOT_ADMINS to the correct user id. However, it bombs out here and I'm not sure why.

**For the rest of the config**
    "initial_intents": "all",
    "intents": ["guilds","members","bans","emojis","integrations","webhooks","invites","voice_states","presences","guild_messages","dm_messages","guild_reactions",
    "dm_reactions", "guild_typing", "dm_typing", "message_content", "guild_scheduled_events", "auto_moderation", "auto_moderation_configuration", "auto_moderation_execution"
    ]

**For debugging, I gave it all intents I could think of. Also tried with:**

    "initial_intents": "all",
    "intents": [ ]

**RE: Discord Intents/Perms**
I also gave it all the intents & perms on Discord.

This was the version installed from pip for both errbot and err-backend-discord.

If you need more information let me know.

**Documentation wise for fresh installs**
Its probably worth noting the fact you need an @ for the discord name and BOT_EXTRA_BACKEND_DIR config directive to get to this point. I learned that from looking at github issues. I understand the second one is being fixed but yeah, not sure if you want me to do a pull request for that or just do it yourself.

**Comment by futex** [comment]
I have the same error, but it seem this project is dead :/

**Comment by nzlosh** [comment]
I've not had enough free time to dedicate to working on the discord backend over the last few months.  If someone else is willing to step up to help with getting the fixes done, I'm more than happy to merge and release on pypi.

**Comment by nzlosh** [comment]
https://github.com/errbotio/err-backend-discord/tree/fix_person I've made the progress available in this branch for people to continue working on it and eventually have it merged to master.
